name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  # Frameworks
  flutter:
    sdk: flutter

  # DI
  dino: ^1.0.0-pre.1
  dino_flutter: ^1.0.0-pre.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Model
  freezed_annotation: ^2.2.0
  fpdart: ^0.5.0

  # Downloader
  flutter_download_manager: ^0.5.5
  path_provider: ^2.0.14
  path: ^1.8.2

  # ViewModel
  flutter_bloc: ^8.1.2

  # UI
  open_filex: ^4.3.2

dev_dependencies:
  # Lints
  flutter_lints: ^2.0.0

  # Generators
  build_runner: ^2.3.3
  freezed: ^2.3.2
  dino_generator: ^1.0.0-pre.4

flutter:
  generate: true
  uses-material-design: true
