name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  # Frameworks
  flutter:
    sdk: flutter

  # DI
  dino: ^1.0.0-pre.1
  dino_flutter: ^1.0.0-pre.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  # Lints
  flutter_lints: ^2.0.0

  # Generators
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

flutter:
  uses-material-design: true
